name: etic
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel=5.1.4
  - matplotlib=3.1.3
  - numpy=1.18.1
  - pathos=0.2.8
  - pot=0.6.0
  - python=3.6.10
  - scikit-learn=0.24.2
  - scipy=1.5.2
  - seaborn=0.11.2
